project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~
website:
  title: "Aria's Little Corner of the (spider)Web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - MiniMapProject.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


