project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~
website:
  title: "Aria's Little Corner of the (spider)Web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Projects"
        menu:
          - text: "Mini Project #1"
            href: MiniMapProject.qmd
          - text: "Mini Project #2"
            href: MP2.qmd 


format:
  html:
    theme: 
      light: stylelight.scss
      dark: darkly
    css: styles.css
    toc: true

editor: visual

